export type { VolunteerEvent, Badge, Milestone, VolunteerStats } from "./types";
import type { VolunteerEvent, Badge, Milestone, VolunteerStats } from "./types";

export const events: VolunteerEvent[] = [
  {
    id: "1",
    title: "Food Bank Saturday",
    organization: "Community Cares Food",
    location: "Evansville, IN",
    date: "2026-03-07",
    time: "9:00 AM - 1:00 PM",
    spotsLeft: 8,
    totalSpots: 20,
    category: "Food & Hunger",
    matchPercent: 95,
    distance: "2.3 mi",
    image: "🥫",
    description: "Help sort and distribute food to families in need at the community food bank. No experience necessary — just bring your energy and a willingness to make a difference.",
    lat: 37.9716,
    lng: -87.5711,
  },
  {
    id: "2",
    title: "Park Cleanup Day",
    organization: "Green Evansville",
    location: "Evansville, IN",
    date: "2026-03-14",
    time: "8:00 AM - 12:00 PM",
    spotsLeft: 15,
    totalSpots: 30,
    category: "Environment",
    matchPercent: 88,
    distance: "1.1 mi",
    image: "🌳",
    description: "Join us for a community park cleanup. Supplies provided. Help us keep our green spaces beautiful for everyone in the neighborhood.",
    lat: 37.9748,
    lng: -87.5580,
  },
  {
    id: "3",
    title: "Habitat for Humanity",
    organization: "Habitat for Humanity",
    location: "Evansville, IN",
    date: "2026-03-21",
    time: "7:00 AM - 3:00 PM",
    spotsLeft: 5,
    totalSpots: 15,
    category: "Housing",
    matchPercent: 91,
    distance: "2.5 mi",
    image: "🏠",
    description: "Help build affordable housing for families in need. Construction skills welcome but not required. Supervisors will guide all volunteers through safe practices.",
    lat: 37.9690,
    lng: -87.5550,
  },
  {
    id: "4",
    title: "Animal Shelter",
    organization: "Vanderburgh Humane Society",
    location: "Evansville, IN",
    date: "2026-03-28",
    time: "10:00 AM - 2:00 PM",
    spotsLeft: 10,
    totalSpots: 12,
    category: "Animals",
    matchPercent: 83,
    distance: "3.0 mi",
    image: "🐕",
    description: "Walk dogs, socialize cats, and help with shelter maintenance. Your time makes a huge difference in the lives of animals waiting for their forever homes.",
    lat: 37.9820,
    lng: -87.5450,
  },
  {
    id: "5",
    title: "Youth Mentoring",
    organization: "Big Brothers Big Sisters",
    location: "Evansville, IN",
    date: "2026-04-04",
    time: "3:00 PM - 5:00 PM",
    spotsLeft: 3,
    totalSpots: 10,
    category: "Education",
    matchPercent: 76,
    distance: "5.6 mi",
    image: "📚",
    description: "Mentor local youth through academic and personal development activities. Be a positive role model and help shape the future of our community's children.",
    lat: 37.9650,
    lng: -87.5800,
  },
  {
    id: "6",
    title: "Senior Center Visit",
    organization: "Evansville Senior Care",
    location: "Evansville, IN",
    date: "2026-04-11",
    time: "1:00 PM - 4:00 PM",
    spotsLeft: 12,
    totalSpots: 20,
    category: "Elderly Care",
    matchPercent: 80,
    distance: "4.2 mi",
    image: "🤝",
    description: "Spend time with seniors — play games, read, or just have a chat. Your companionship makes a profound difference in the lives of our elderly community members.",
    lat: 37.9780,
    lng: -87.5620,
  },
  {
    id: "7",
    title: "River Cleanup",
    organization: "Ohio River Foundation",
    location: "Evansville, IN",
    date: "2026-04-18",
    time: "8:00 AM - 11:00 AM",
    spotsLeft: 20,
    totalSpots: 40,
    category: "Environment",
    matchPercent: 85,
    distance: "3.8 mi",
    image: "🌊",
    description: "Help clean up the Ohio River banks and protect local wildlife. Gloves and bags provided. Together we can restore the natural beauty of our waterways.",
    lat: 37.9600,
    lng: -87.5900,
  },
  {
    id: "8",
    title: "Literacy Workshop",
    organization: "Read to Succeed",
    location: "Evansville, IN",
    date: "2026-04-25",
    time: "4:00 PM - 6:00 PM",
    spotsLeft: 6,
    totalSpots: 8,
    category: "Education",
    matchPercent: 72,
    distance: "2.1 mi",
    image: "📖",
    description: "Help children improve their reading skills through fun activities and one-on-one tutoring sessions. Make literacy accessible and enjoyable for every child.",
    lat: 37.9730,
    lng: -87.5680,
  },
];

export const badges: Badge[] = [
  { id: "1", name: "First Time", icon: "🎯", color: "#2D8CFF", earned: true, verified: true },
  { id: "2", name: "Habitat Build", subtitle: "Community Star", icon: "🏠", color: "#FF8C42", earned: true, verified: true },
  { id: "3", name: "Youth Mentoring", icon: "📚", color: "#E74C3C", earned: true, verified: false },
  { id: "4", name: "Animal Shelter", icon: "🐕", color: "#27AE60", earned: true, verified: true },
  { id: "5", name: "Food Drive Hero", icon: "🥫", color: "#F39C12", earned: false, verified: false },
  { id: "6", name: "100 Hour Club", icon: "⭐", color: "#6C5CE7", earned: false, verified: false },
];

export const volunteerStats: VolunteerStats = {
  totalHours: 47.5,
  sessions: 12,
  impactPoints: 1188,
  monthlyHours: [
    { month: "Jul", hours: 6 },
    { month: "Aug", hours: 8 },
    { month: "Sep", hours: 5 },
    { month: "Oct", hours: 10 },
    { month: "Nov", hours: 7 },
    { month: "Dec", hours: 4 },
    { month: "Jan", hours: 3 },
    { month: "Feb", hours: 4.5 },
  ],
};

export const milestones: Milestone[] = [
  { label: "First Volunteer Session", progress: 100, icon: "🎯" },
  { label: "10 Hours Volunteered", progress: 100, icon: "⏰" },
  { label: "25 Hours Volunteered", progress: 100, icon: "🏅" },
  { label: "50 Hours Volunteered", progress: 95, icon: "🏆" },
  { label: "Community Leader", progress: 60, icon: "👑" },
  { label: "100 Hour Club", progress: 47, icon: "⭐" },
];

export const categories = [
  "All",
  "Food & Hunger",
  "Environment",
  "Housing",
  "Animals",
  "Education",
  "Elderly Care",
];
